baseURL = "/"
languageCode = "en-us"
defaultContentLanguage = "en"
theme = "almeida-cv"
title = "Zachery Thomas"

[params]
colorDark = "#666"
colorLight = "#fff"
colorPageBackground = "#ddd"
colorPrimary = "#3636c9"
colorPrimaryText = "#fff"
colorRightColumnBackground = "#f5f5f5"
colorSecondary = "#aaa"
pages = 1
